/:
  controller: general
  action: home
  security:
    rule: default

/admin/dashboard:
  controller: admin
  action: dashboard
  security:
    rule: admin
puis rajouter à la suite :
# catégorie

/categorie/new:
  controller: categorie
  action: create
  security:
    rule: admin

/categorie:
  controller: categorie
  action: read
  security:
    rule : default

/categorie/categories:
  controller: categorie
  action: listCategories
  security:
    rule: default

/categorie/delete:
  controller: categorie
  action: delete
  security:
    rule: admin
