/:
  controller: general
  action: home
  security:
    rule: default

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/admin/dashboard:
  controller: admin
  action: dashboard
  security:
    rule: admin



# page

/page/new:
  controller: page
  action: create
  security:
    rule: author

/page:
  controller: page
  action: read
  security:
    rule: default

/page/pages:
  controller: page
  action: listPages
  security:
    rule: default

/page/delete:
  controller: page
  action: delete
  security:
    rule:
      delete:
        page

/page/update:
  controller: page
  action: update
  security:
    rule:
      update: page



# personnage

/personnage/new:
  controller: personnage
  action: create
  security:
    rule: admin

/personnage:
  controller: personnage
  action: read
  security:
    rule: default

/personnage/delete:
  controller: personnage
  action: delete
  security:
    rule: admin



# user

/admin/users:
  controller: admin
  action: listUsers
  security:
    rule: admin

/user/delete:
  controller: user
  action: delete
  security:
    rule: admin

/user/update:
  controller: user
  action: update
  security:
    rule:
      update: user



# catégorie

/categorie/new:
  controller: categorie
  action: create
  security:
    rule: admin

/categorie:
  controller: categorie
  action: read
  security:
    rule : default

/categorie/categories:
  controller: categorie
  action: listCategories
  security:
    rule: default

/categorie/delete:
  controller: categorie
  action: delete
  security:
    rule: admin



# commentaire

/commentaire/new:
  controller: commentaire
  action: create
  security:
    rule: user

/commentaire/signaler:
  controller: signalement
  action: signaler
  security:
    rule: default

/admin/signalements:
  controller: admin
  action: listSignalements
  security:
    rule: admin

/commentaire:
  controller: commentaire
  action: read
  security:
    rule :
      delete : commentaire

/commentaire/delete:
  controller: commentaire
  action: delete
  security:
    rule :
      delete : commentaire




# recherche
/recherche:
  controller: recherche
  action: recherche
  security:
    rule: default